version: '3.7'

services:
  vue-app:
    ports:
      - 88:3000
    container_name: vue-app
    image: app-tesis-front:latest
    environment:
      - VITE_API_URL=http://161.132.40.114:89/api
    networks:
      - red-tesis

networks:
  red-tesis:
    driver: bridge

