# # nginx.conf
# server {
#     listen 80;  # Nginx escuchará en el puerto 80 dentro del contenedor

#     server_name localhost;  # Puedes cambiar esto si tienes un dominio

#     # Ruta raíz de la aplicación (directorio donde se guardarán los archivos generados)
#     root /usr/share/nginx/html;

#     # Página de inicio por defecto
#     index index.html;

#     # Ubicación para servir archivos estáticos de Vue.js
#     location / {
#         try_files $uri $uri/ /index.html;  # Redirige todas las rutas a index.html (Single Page Application)
#     }

#     # Página de error para cuando no encuentra recursos
#     error_page 404 /index.html;

#     # Configuración de compresión
#     gzip on;
#     gzip_types text/plain application/xml text/css application/javascript;
#     gzip_min_length 1000;
# }
