<template>
  <div class="report-container">
    <CButton color="secondary" @click="goBack" class="back-button">
      ← Regresar
    </CButton>
    <h1 class="report-title">Reporte de Asistencia</h1>

    <div v-if="loading" class="loading-container">
      <p class="loading-text">Cargando...</p>
    </div>

    <div v-else-if="assistenceData.length > 0">
      <div class="table-wrapper rp-scroll-x">
        <table class="attendance-table">
          <thead>
            <tr>
              <th>Estudiante</th>
              <th class="text-center">Asistió</th>
              <th class="text-center">Faltó</th>
              <th class="text-center">Tardanza</th>
              <th class="text-center">Falta Justificada</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(student, index) in assistenceData" :key="index">
              <td>{{ student.student_name }}</td>
              <td class="text-center">{{ student.assistances.asistio }}</td>
              <td class="text-center">{{ student.assistances.falto }}</td>
              <td class="text-center">{{ student.assistances.tardanza }}</td>
              <td class="text-center">{{ student.assistances.falta_justificada }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <p v-else class="list-empty-message py-4 text-center">
      No hay registros para mostrar.
    </p>
    <div class="div-pdf" v-if="assistenceData.length > 0">
      <CButton color="primary" @click="generatePDF" class="pdf-button">
        Generar PDF
      </CButton>
      <CButton color="success" @click="exportToExcel" class="excel-button text-white">
        Generar Excel
      </CButton>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import AssistanceService from "@/services/AssistanceService"
import jsPDF from 'jspdf'
import autoTable from "jspdf-autotable";
import xlsx from 'xlsx/dist/xlsx.full.min';

const route = useRoute()
const router = useRouter()

const course_class_id = ref(Number(route.params.course_class_id) || 0)
const assistenceData = ref([])
const loading = ref(true)

const fetchData = async () => {
  loading.value = true
  if (course_class_id.value) {
    try {
      const response = await AssistanceService.getReport(course_class_id.value)

      if (response.data.success) {
        assistenceData.value = Object.values(response.data.data)
      }
    } catch (error) {
      console.error("Error al cargar los datos:", error)
    }
  }
  loading.value = false
}

const goBack = () => {
  router.back()
}

const generatePDF = () => {
  const doc = new jsPDF({
    orientation: 'landscape', // Use landscape orientation for wider tables
    unit: 'mm', // Set units to millimeters for better control
    format: 'a4' // Use A4 paper size
  });

  doc.setFontSize(16); // Adjust font size for better readability
  doc.text('Reporte de Asistencia', 10, 20); // Center the title

  // Add a header row with the course name (if available)
  const courseName = 'Curso de Matemáticas'; // Replace with actual course name
  doc.setFontSize(14);
  doc.text(courseName, doc.internal.pageSize.getWidth() / 2, 28, { align: 'center' }); 

  // Set table headers and data
  const headers = ['ESTUDIANTE', 'Asistió', 'Faltó', 'Tardanza', 'Falta Justificada'];
  const data = assistenceData.value.map(student => [
    student.student_name,
    student.assistances.asistio,
    student.assistances.falto,
    student.assistances.tardanza,
    student.assistances.falta_justificada
  ]);

  // Draw the table
  doc.autoTable({
    head: [headers],
    body: data,
    startY: 40, // Set startY to 40 to position the table below the header
    theme: 'grid',
    styles: {
      fontSize: 10, // Adjust font size within the table
      cellPadding: 5, // Add padding for better spacing
      overflow: 'linebreak', // Allow text to wrap within cells
      halign: 'center' // Center text in each column
    }
  });

  // Add a footer with the date and the report generated by
  const date = new Date().toLocaleDateString('es-PE');
  doc.setFontSize(10);
  doc.text(`Generado el ${date}`, doc.internal.pageSize.getWidth() / 2, doc.autoTable.previous.finalY + 10, { align: 'center' });

  // Save the PDF
  doc.save('reporte_asistencia.pdf');
};

const exportToExcel = () => {
  const XLSX = xlsx;
      const workbook = XLSX.utils.book_new();
      const worksheet = XLSX.utils.json_to_sheet(assistenceData.value.map(student => ({
        Estudiante: student.student_name, 
        asistio: student.assistances.asistio, 
        falto: student.assistances.falto, 
        tardanza: student.assistances.tardanza, 
        Falta_Justificada: student.assistances.falta_justificada
    })));
      XLSX.utils.book_append_sheet(workbook, worksheet, "framework");
      XLSX.writeFile(workbook, "framework.xlsx");
};
onMounted(fetchData)
</script>

<style scoped>
.report-container {
  max-width: var(--rp-page-max-width);
  margin: 0 auto;
  padding: var(--rp-space-5);
  background: var(--rp-surface);
  border: 1px solid var(--rp-border);
  border-radius: var(--rp-radius-lg);
  box-shadow: var(--rp-shadow-xs);
}

.report-title {
  margin: var(--rp-space-4) 0 var(--rp-space-5);
  font-size: var(--rp-text-2xl);
  font-weight: var(--rp-weight-semibold);
  line-height: var(--rp-leading-tight);
  letter-spacing: -0.02em;
  color: var(--rp-text-heading);
}

.table-wrapper {
  margin-top: var(--rp-space-5);
  border: 1px solid var(--rp-border);
  border-radius: var(--rp-radius-lg);
}

/* Cinco columnas no caben en móvil: se fija un mínimo y el wrapper hace scroll. */
.attendance-table {
  width: 100%;
  min-width: 34rem;
  border-collapse: collapse;
}

.attendance-table th,
.attendance-table td {
  padding: var(--rp-space-3);
  text-align: start;
  font-size: var(--rp-text-base);
  border-bottom: 1px solid var(--rp-table-row-border);
}

.attendance-table th {
  background-color: var(--rp-table-head-bg);
  color: var(--rp-table-head-color);
  font-size: var(--rp-text-2xs);
  font-weight: var(--rp-weight-semibold);
  text-transform: uppercase;
  letter-spacing: var(--rp-tracking-wide);
  white-space: nowrap;
  border-bottom: 1px solid var(--rp-table-head-border);
}

.attendance-table td {
  color: var(--rp-text);
}

.attendance-table tbody tr {
  transition: background-color var(--rp-transition-fast);
}

.attendance-table tbody tr:hover {
  background-color: var(--rp-table-row-hover);
}

.attendance-table tbody tr:last-child td {
  border-bottom: none;
}

.loading-container {
  text-align: center;
  padding: var(--rp-space-10) var(--rp-space-4);
}

.loading-text {
  margin: 0;
  font-size: var(--rp-text-md);
  color: var(--rp-text-muted);
}

.div-pdf {
  display: flex;
  flex-wrap: wrap;
  gap: var(--rp-space-2);
  margin: var(--rp-space-5) 0 0;
}

@media (max-width: 767.98px) {
  .report-container {
    padding: var(--rp-space-4);
  }

  .report-title {
    font-size: var(--rp-text-xl);
  }

  .attendance-table th,
  .attendance-table td {
    padding: var(--rp-space-2);
    font-size: var(--rp-text-sm);
  }
}

@media (max-width: 575.98px) {
  .div-pdf > .btn {
    flex: 1 1 auto;
  }
}
</style>
